version: '3.8'

services:
  postgres:
    image: postgres
    container_name: dust_postgres
    restart: always
    environment:
      POSTGRES_USER: dust_admin
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: market_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  mongodb:
    image: mongo
    container_name: dust_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dust_admin
      MONGO_INITDB_ROOT_PASSWORD: secret_password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  pg_data:
  mongo_data:
